"""Entity definitions for Ecotrend sensors."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

from homeassistant.components.sensor import SensorDeviceClass, SensorEntityDescription, SensorStateClass
from homeassistant.const import EntityCategory, UnitOfEnergy, UnitOfVolume

from .const import (
    CONF_TYPE_HEATING,
    CONF_TYPE_HEATING_CASH,
    CONF_TYPE_HEATING_CUSTOM,
    CONF_TYPE_HEATWATER,
    CONF_TYPE_HEATWATER_CASH,
    CONF_TYPE_HEATWATER_CUSTOM,
    CONF_TYPE_WATER,
    CONF_TYPE_WATER_CASH,
    CONF_TYPE_WATER_CUSTOM,
    CONF_TYPE_ELECTRICITY,
    CONF_TYPE_ELECTRICITY_CONSUMPTION,
    CONF_TYPE_ELECTRICITY_CONSUMPTION_DAY,
    CONF_TYPE_ELECTRICITY_CONSUMPTION_WEEK,
    CONF_TYPE_ELECTRICITY_CONSUMPTION_MONTH,
    CONF_TYPE_ELECTRICITY_CONSUMPTION_YEAR,
    CONF_TYPE_ELECTRICITY_CASH,
    CONF_TYPE_ELECTRICITY_CASH_DAY,
    CONF_TYPE_ELECTRICITY_CASH_BILLING,
    CONF_TYPE_ELECTRICITY_CASH_WEEK,
    CONF_TYPE_ELECTRICITY_CASH_MONTH,
    CONF_TYPE_ELECTRICITY_CASH_YEAR,
    CONF_TYPE_HEATING_CONSUMPTION,
    CONF_TYPE_HEATING_CONSUMPTION_DAY,
    CONF_TYPE_HEATING_CONSUMPTION_WEEK,
    CONF_TYPE_HEATING_CONSUMPTION_MONTH,
    CONF_TYPE_HEATING_CONSUMPTION_YEAR,
    CONF_TYPE_HEATING_CASH_BILLING,
    CONF_TYPE_HEATING_CASH_DAY,
    CONF_TYPE_HEATING_CASH_WEEK,
    CONF_TYPE_HEATING_CASH_MONTH,
    CONF_TYPE_HEATING_CASH_YEAR,
)


@dataclass
class EcotrendRequiredKeysMixin:
    """Mixin class for required keys in Ecotrend sensor entity descriptions."""

    data_type: Literal["heating", "warmwater", "water"]
    costs_or_cosums: Literal["consums", "costs"]


@dataclass
class EcotrendSensorEntityDescription(SensorEntityDescription, EcotrendRequiredKeysMixin):
    """Describes an Ecotrend sensor entity."""


SENSOR_TYPES: tuple[EcotrendSensorEntityDescription, ...] = (
    EcotrendSensorEntityDescription(
        key=CONF_TYPE_HEATWATER,
        data_type=CONF_TYPE_HEATWATER,
        native_unit_of_measurement=UnitOfVolume.CUBIC_METERS,
        device_class=SensorDeviceClass.WATER,
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:thermometer-water",
        costs_or_cosums="consums",
    ),
    EcotrendSensorEntityDescription(
        key=CONF_TYPE_HEATWATER_CASH,
        data_type=CONF_TYPE_HEATWATER,
        device_class=SensorDeviceClass.MONETARY,
        state_class=SensorStateClass.TOTAL,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:cash",
        costs_or_cosums="costs",
    ),
    EcotrendSensorEntityDescription(
        key=CONF_TYPE_HEATWATER_CUSTOM,
        data_type=CONF_TYPE_HEATWATER,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:thermometer-water",
        costs_or_cosums="consums",
    ),
    EcotrendSensorEntityDescription(
        key=CONF_TYPE_WATER,
        data_type=CONF_TYPE_WATER,
        native_unit_of_measurement=UnitOfVolume.CUBIC_METERS,
        device_class=SensorDeviceClass.WATER,
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:water",
        costs_or_cosums="consums",
    ),
    EcotrendSensorEntityDescription(
        key=CONF_TYPE_WATER_CASH,
        data_type=CONF_TYPE_WATER,
        device_class=SensorDeviceClass.MONETARY,
        state_class=SensorStateClass.TOTAL,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:cash",
        costs_or_cosums="costs",
    ),
    EcotrendSensorEntityDescription(
        key=CONF_TYPE_WATER_CUSTOM,
        data_type=CONF_TYPE_WATER,
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:water",
        costs_or_cosums="consums",
    ),
    EcotrendSensorEntityDescription(
        key=CONF_TYPE_HEATING,
        data_type=CONF_TYPE_HEATING,
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:radiator",
        costs_or_cosums="consums",
    ),
    EcotrendSensorEntityDescription(
        key=CONF_TYPE_HEATING_CASH,
        data_type=CONF_TYPE_HEATING,
        device_class=SensorDeviceClass.MONETARY,
        state_class=SensorStateClass.TOTAL,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:cash",
        costs_or_cosums="costs",
    ),
    EcotrendSensorEntityDescription(
        key=CONF_TYPE_HEATING_CUSTOM,
        data_type=CONF_TYPE_HEATING,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_category=EntityCategory.DIAGNOSTIC,
        icon="mdi:radiator",
        costs_or_cosums="consums",
    ),
)


@dataclass
class DkSensorDescription(SensorEntityDescription):
    """Describes a DK sensor entity."""

    data_type: Literal["electricity", "heating"] = ""
    costs_or_cosums: Literal["consums", "costs"] = "consums"
    unit_key: str = ""
    display_name: str = ""
    entity_category: EntityCategory | None = None
    state_class: SensorStateClass | None = None


DK_SENSOR_TYPES: tuple[DkSensorDescription, ...] = (
    DkSensorDescription(
        key=CONF_TYPE_ELECTRICITY_CONSUMPTION,
        icon="mdi:lightning-bolt",
        unit_key="electricity_unit",
        data_type=CONF_TYPE_ELECTRICITY,
        costs_or_cosums="consums",
        device_class=SensorDeviceClass.ENERGY,
        display_name="Electricity Consumption",
        entity_category=EntityCategory.DIAGNOSTIC,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    DkSensorDescription(
        key=CONF_TYPE_ELECTRICITY_CONSUMPTION_DAY,
        icon="mdi:lightning-bolt",
        unit_key="electricity_unit",
        data_type=CONF_TYPE_ELECTRICITY,
        costs_or_cosums="consums",
        device_class=SensorDeviceClass.ENERGY,
        display_name="Electricity Daily Consumption",
        entity_category=EntityCategory.DIAGNOSTIC,
        state_class=SensorStateClass.TOTAL,
    ),
    DkSensorDescription(
        key=CONF_TYPE_ELECTRICITY_CONSUMPTION_WEEK,
        icon="mdi:lightning-bolt",
        unit_key="electricity_unit",
        data_type=CONF_TYPE_ELECTRICITY,
        costs_or_cosums="consums",
        device_class=SensorDeviceClass.ENERGY,
        display_name="Electricity Weekly Consumption",
        entity_category=EntityCategory.DIAGNOSTIC,
        state_class=SensorStateClass.TOTAL,
    ),
    DkSensorDescription(
        key=CONF_TYPE_ELECTRICITY_CONSUMPTION_MONTH,
        icon="mdi:lightning-bolt",
        unit_key="electricity_unit",
        data_type=CONF_TYPE_ELECTRICITY,
        costs_or_cosums="consums",
        device_class=SensorDeviceClass.ENERGY,
        display_name="Electricity Monthly Consumption",
        entity_category=EntityCategory.DIAGNOSTIC,
        state_class=SensorStateClass.TOTAL,
    ),
    DkSensorDescription(
        key=CONF_TYPE_ELECTRICITY_CONSUMPTION_YEAR,
        icon="mdi:lightning-bolt",
        unit_key="electricity_unit",
        data_type=CONF_TYPE_ELECTRICITY,
        costs_or_cosums="consums",
        device_class=SensorDeviceClass.ENERGY,
        display_name="Electricity Yearly Consumption",
        entity_category=EntityCategory.DIAGNOSTIC,
        state_class=SensorStateClass.TOTAL,
    ),
    DkSensorDescription(
        key=CONF_TYPE_ELECTRICITY_CASH_DAY,
        icon="mdi:cash",
        unit_key="currency_unit",
        data_type=CONF_TYPE_ELECTRICITY,
        costs_or_cosums="costs",
        device_class=SensorDeviceClass.MONETARY,
        display_name="Electricity Economy Daily",
        entity_category=EntityCategory.DIAGNOSTIC,
        state_class=SensorStateClass.TOTAL,
    ),
    DkSensorDescription(
        key=CONF_TYPE_ELECTRICITY_CASH_WEEK,
        icon="mdi:cash",
        unit_key="currency_unit",
        data_type=CONF_TYPE_ELECTRICITY,
        costs_or_cosums="costs",
        device_class=SensorDeviceClass.MONETARY,
        display_name="Electricity Economy Weekly",
        entity_category=EntityCategory.DIAGNOSTIC,
        state_class=SensorStateClass.TOTAL,
    ),
    DkSensorDescription(
        key=CONF_TYPE_ELECTRICITY_CASH_MONTH,
        icon="mdi:cash",
        unit_key="currency_unit",
        data_type=CONF_TYPE_ELECTRICITY,
        costs_or_cosums="costs",
        device_class=SensorDeviceClass.MONETARY,
        display_name="Electricity Economy Monthly",
        entity_category=EntityCategory.DIAGNOSTIC,
        state_class=SensorStateClass.TOTAL,
    ),
    DkSensorDescription(
        key=CONF_TYPE_ELECTRICITY_CASH_YEAR,
        icon="mdi:cash",
        unit_key="currency_unit",
        data_type=CONF_TYPE_ELECTRICITY,
        costs_or_cosums="costs",
        device_class=SensorDeviceClass.MONETARY,
        display_name="Electricity Economy Yearly",
        entity_category=EntityCategory.DIAGNOSTIC,
        state_class=SensorStateClass.TOTAL,
    ),
    DkSensorDescription(
        key=CONF_TYPE_ELECTRICITY_CASH_BILLING,
        icon="mdi:cash",
        unit_key="currency_unit",
        data_type=CONF_TYPE_ELECTRICITY,
        costs_or_cosums="costs",
        device_class=SensorDeviceClass.MONETARY,
        display_name="Electricity Economy",
        entity_category=EntityCategory.DIAGNOSTIC,
        state_class=SensorStateClass.TOTAL,
    ),
    DkSensorDescription(
        key=CONF_TYPE_HEATING_CONSUMPTION,
        icon="mdi:radiator",
        unit_key="heat_unit",
        data_type=CONF_TYPE_HEATING,
        costs_or_cosums="consums",
        display_name="Heat Consumption",
        entity_category=EntityCategory.DIAGNOSTIC,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    DkSensorDescription(
        key=CONF_TYPE_HEATING_CONSUMPTION_DAY,
        icon="mdi:radiator",
        unit_key="heat_unit",
        data_type=CONF_TYPE_HEATING,
        costs_or_cosums="consums",
        display_name="Heat Daily Consumption",
        entity_category=EntityCategory.DIAGNOSTIC,
        state_class=SensorStateClass.TOTAL,
    ),
    DkSensorDescription(
        key=CONF_TYPE_HEATING_CONSUMPTION_WEEK,
        icon="mdi:radiator",
        unit_key="heat_unit",
        data_type=CONF_TYPE_HEATING,
        costs_or_cosums="consums",
        display_name="Heat Weekly Consumption",
        entity_category=EntityCategory.DIAGNOSTIC,
        state_class=SensorStateClass.TOTAL,
    ),
    DkSensorDescription(
        key=CONF_TYPE_HEATING_CONSUMPTION_MONTH,
        icon="mdi:radiator",
        unit_key="heat_unit",
        data_type=CONF_TYPE_HEATING,
        costs_or_cosums="consums",
        display_name="Heat Monthly Consumption",
        entity_category=EntityCategory.DIAGNOSTIC,
        state_class=SensorStateClass.TOTAL,
    ),
    DkSensorDescription(
        key=CONF_TYPE_HEATING_CONSUMPTION_YEAR,
        icon="mdi:radiator",
        unit_key="heat_unit",
        data_type=CONF_TYPE_HEATING,
        costs_or_cosums="consums",
        display_name="Heat Yearly Consumption",
        entity_category=EntityCategory.DIAGNOSTIC,
        state_class=SensorStateClass.TOTAL,
    ),
    DkSensorDescription(
        key=CONF_TYPE_HEATING_CASH_DAY,
        icon="mdi:cash",
        unit_key="currency_unit",
        data_type=CONF_TYPE_HEATING,
        costs_or_cosums="costs",
        device_class=SensorDeviceClass.MONETARY,
        display_name="Heat Economy Daily",
        entity_category=EntityCategory.DIAGNOSTIC,
        state_class=SensorStateClass.TOTAL,
    ),
    DkSensorDescription(
        key=CONF_TYPE_HEATING_CASH_WEEK,
        icon="mdi:cash",
        unit_key="currency_unit",
        data_type=CONF_TYPE_HEATING,
        costs_or_cosums="costs",
        device_class=SensorDeviceClass.MONETARY,
        display_name="Heat Economy Weekly",
        entity_category=EntityCategory.DIAGNOSTIC,
        state_class=SensorStateClass.TOTAL,
    ),
    DkSensorDescription(
        key=CONF_TYPE_HEATING_CASH_MONTH,
        icon="mdi:cash",
        unit_key="currency_unit",
        data_type=CONF_TYPE_HEATING,
        costs_or_cosums="costs",
        device_class=SensorDeviceClass.MONETARY,
        display_name="Heat Economy Monthly",
        entity_category=EntityCategory.DIAGNOSTIC,
        state_class=SensorStateClass.TOTAL,
    ),
    DkSensorDescription(
        key=CONF_TYPE_HEATING_CASH_YEAR,
        icon="mdi:cash",
        unit_key="currency_unit",
        data_type=CONF_TYPE_HEATING,
        costs_or_cosums="costs",
        device_class=SensorDeviceClass.MONETARY,
        display_name="Heat Economy Yearly",
        entity_category=EntityCategory.DIAGNOSTIC,
        state_class=SensorStateClass.TOTAL,
    ),
    DkSensorDescription(
        key=CONF_TYPE_WATER_CASH,
        icon="mdi:cash",
        unit_key="currency_unit",
        data_type=CONF_TYPE_HEATING,
        costs_or_cosums="costs",
        device_class=SensorDeviceClass.MONETARY,
        display_name="Heat Economy",
        entity_category=EntityCategory.DIAGNOSTIC,
        state_class=SensorStateClass.TOTAL,
    ),
    DkSensorDescription(
        key=CONF_TYPE_HEATING_CASH_BILLING,
        icon="mdi:cash",
        unit_key="currency_unit",
        data_type=CONF_TYPE_HEATING,
        costs_or_cosums="costs",
        device_class=SensorDeviceClass.MONETARY,
        display_name="Heat Economy",
        entity_category=EntityCategory.DIAGNOSTIC,
        state_class=SensorStateClass.TOTAL,
    ),
)
